version: "3.9"

services:
  solana-exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: solana-th-exporter
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
    command: ["./solana-th-exporter", "-a", "DeutWrchKzcSZM9HxoXkpGfYhMVzFabkf5NQvSKDUYJ5", "-o", "10"]